#!/usr/bin/env node
/**
 * Screenshots every `tour--*` story listed in catalog.mjs at desktop
 * (1440×900) or phone (390×844), deviceScaleFactor 2, and writes
 * `.media-out/raw/shots/<name>.png` (encode.sh turns them into WebP), plus
 * `.media-out/manifest.json` and `.media-out/report.json`.
 *
 * Env: MEDIA_BASE_URL, MEDIA_OUT_DIR, MEDIA_FILTER (substring of shot name).
 * A filtered run shoots only the matching shots and keeps the other PNGs; it
 * still writes the full manifest (every shot in the catalog), but report.json
 * covers only the shots it took. An unfiltered run first deletes raw/shots/,
 * so shots removed from the catalog don't linger.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  chromium, OUT_DIR, FILTER, waitForLadle, storyUrl, newCaptureContext, watchPage, waitForSettled, findForbiddenText, sleep,
} from './lib.mjs';
import { SHOTS, VIDEOS, SECTIONS } from './catalog.mjs';

/** Page tweaks a shot can ask for (`prepare` in catalog.mjs), run just before the screenshot. */
const PREPARE = {
  // Threads open scrolled to the newest reply, which on a phone leaves the
  // first reply's name row cut in half under the original message. Show the
  // thread from its first reply instead (all five replies still fit).
  async threadFromTop(page) {
    const moved = await page.evaluate(() => {
      const label = Array.from(document.querySelectorAll('.MuiTypography-caption')).find(
        (el) => el.textContent?.trim() === 'Original message',
      );
      const replies = label?.parentElement?.nextElementSibling;
      if (!replies) return false;
      replies.scrollTop = 0;
      return true;
    });
    if (!moved) throw new Error('threadFromTop: no thread reply list');
    await sleep(400);
  },
};

async function shoot(browser, shot) {
  const context = await newCaptureContext(browser, shot.viewport);
  const page = await context.newPage();
  const issues = watchPage(page);
  let brokenImages = 0;
  let forbidden = [];
  let error = null;
  try {
    await page.goto(storyUrl(shot.story), { waitUntil: 'networkidle', timeout: 45_000 });
    await waitForSettled(page, { settleMs: shot.settleMs ?? 2500 });
    // Park the mouse off-canvas so no hover state leaks into the shot.
    await page.mouse.move(0, 0);
    if (shot.prepare) await PREPARE[shot.prepare](page);
    // Check the frame that is actually captured: the mouse move and `prepare`
    // can change what's on screen (a scroll can bring new images into view),
    // so wait for anything they started and only then look for problems.
    brokenImages = await waitForSettled(page, { settleMs: 0 });
    forbidden = await findForbiddenText(page);
    await page.screenshot({ path: path.join(OUT_DIR, 'raw', 'shots', `${shot.name}.png`) });
  } catch (err) {
    error = String(err?.message || err);
  } finally {
    await context.close();
  }
  return { name: shot.name, story: shot.story, viewport: shot.viewport, error, brokenImages, forbidden, ...issues };
}

async function main() {
  await waitForLadle();
  // A full run starts clean so renamed/removed shots don't linger.
  if (!FILTER) await rm(path.join(OUT_DIR, 'raw', 'shots'), { recursive: true, force: true });
  await mkdir(path.join(OUT_DIR, 'raw', 'shots'), { recursive: true });
  const shots = SHOTS.filter((s) => !FILTER || s.name.includes(FILTER));
  const browser = await chromium.launch();
  const results = [];
  for (const shot of shots) {
    process.stdout.write(`[media:shots] ${shot.name} (${shot.story} @ ${shot.viewport}) ... `);
    const r = await shoot(browser, shot);
    results.push(r);
    const problems = [
      r.error && `error: ${r.error}`,
      r.pageErrors.length && `${r.pageErrors.length} page error(s)`,
      r.renderErrors.length && `${r.renderErrors.length} render error(s)`,
      r.unhandledRequests.length && `${r.unhandledRequests.length} unhandled request(s)`,
      r.brokenImages && `${r.brokenImages} broken image(s)`,
      r.forbidden.length && `forbidden text ${r.forbidden.join(', ')}`,
    ].filter(Boolean);
    console.log(problems.length ? `ISSUES: ${problems.join('; ')}` : 'ok');
  }
  await browser.close();

  const manifest = {
    generatedAt: new Date().toISOString(),
    note: 'Generated by frontend/scripts/media — see docs-site/docs/contributing/regenerating-screenshots.md',
    sections: SECTIONS,
    screenshots: SHOTS.map(({ name, viewport, section, caption, alt, readme }) => ({
      name,
      file: `screenshots/${name}.webp`,
      viewport,
      width: viewport === 'phone' ? 780 : 2880,
      height: viewport === 'phone' ? 1688 : 1800,
      section,
      caption,
      alt,
      readme: !!readme,
    })),
    videos: VIDEOS,
    social: { file: 'social.png', width: 1280, height: 640, alt: 'Semaphore Chat — self-hosted voice and text chat' },
  };
  await writeFile(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2));
  const issueCount = results.filter(
    (r) => r.error || r.pageErrors.length || r.renderErrors.length || r.unhandledRequests.length || r.brokenImages || r.forbidden.length,
  ).length;
  await writeFile(
    path.join(OUT_DIR, 'report.json'),
    // `filter` is set when MEDIA_FILTER limited the run: then `shots` covers only
    // those shots, and publish-media.sh refuses the report.
    JSON.stringify({ generatedAt: new Date().toISOString(), filter: FILTER || null, issueCount, shots: results }, null, 2),
  );
  console.log(`[media:shots] ${results.length} screenshot(s), ${issueCount} with issues — see ${path.join(OUT_DIR, 'report.json')}`);
}

main().catch((err) => {
  console.error('[media:shots] Fatal:', err);
  process.exitCode = 1;
});
