// RBAC Resource Types - keep in sync with backend RbacResourceType enum
export const RBAC_RESOURCES = {
  COMMUNITY: 'COMMUNITY',
  CHANNEL: 'CHANNEL',
  INSTANCE: 'INSTANCE',
  DM_GROUP: 'DM_GROUP',
} as const;

export type RbacResource = typeof RBAC_RESOURCES[keyof typeof RBAC_RESOURCES];

// RBAC Actions mapping - keep in sync with backend RbacActions enum
export const RBAC_ACTIONS = {
  // Message Management
  CREATE_MESSAGE: 'CREATE_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  READ_MESSAGE: 'READ_MESSAGE',

  // Channel Management
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  UPDATE_CHANNEL: 'UPDATE_CHANNEL',
  DELETE_CHANNEL: 'DELETE_CHANNEL',
  READ_CHANNEL: 'READ_CHANNEL',
  JOIN_CHANNEL: 'JOIN_CHANNEL',
  MANAGE_CHANNEL_PERMISSIONS: 'MANAGE_CHANNEL_PERMISSIONS',
  MANAGE_WEBHOOKS: 'MANAGE_WEBHOOKS',

  // Voice
  SPEAK: 'SPEAK',
  VIDEO: 'VIDEO',
  SCREEN_SHARE: 'SCREEN_SHARE',

  // Community Management
  CREATE_COMMUNITY: 'CREATE_COMMUNITY',
  UPDATE_COMMUNITY: 'UPDATE_COMMUNITY',
  DELETE_COMMUNITY: 'DELETE_COMMUNITY',
  READ_COMMUNITY: 'READ_COMMUNITY',
  READ_ALL_COMMUNITIES: 'READ_ALL_COMMUNITIES',

  // Member Management
  CREATE_MEMBER: 'CREATE_MEMBER',
  UPDATE_MEMBER: 'UPDATE_MEMBER',
  DELETE_MEMBER: 'DELETE_MEMBER',
  READ_MEMBER: 'READ_MEMBER',

  // Role Management
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  READ_ROLE: 'READ_ROLE',

  // User Management
  DELETE_USER: 'DELETE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',

  // Invite Management
  CREATE_INVITE: 'CREATE_INVITE',
  DELETE_INVITE: 'DELETE_INVITE',
  CREATE_INSTANCE_INVITE: 'CREATE_INSTANCE_INVITE',
  DELETE_INSTANCE_INVITE: 'DELETE_INSTANCE_INVITE',
  READ_INSTANCE_INVITE: 'READ_INSTANCE_INVITE',
  UPDATE_INSTANCE_INVITE: 'UPDATE_INSTANCE_INVITE',

  // Alias/Mention Groups
  CREATE_ALIAS_GROUP: 'CREATE_ALIAS_GROUP',
  UPDATE_ALIAS_GROUP: 'UPDATE_ALIAS_GROUP',
  DELETE_ALIAS_GROUP: 'DELETE_ALIAS_GROUP',
  READ_ALIAS_GROUP: 'READ_ALIAS_GROUP',
  CREATE_ALIAS_GROUP_MEMBER: 'CREATE_ALIAS_GROUP_MEMBER',
  DELETE_ALIAS_GROUP_MEMBER: 'DELETE_ALIAS_GROUP_MEMBER',
  READ_ALIAS_GROUP_MEMBER: 'READ_ALIAS_GROUP_MEMBER',
  UPDATE_ALIAS_GROUP_MEMBER: 'UPDATE_ALIAS_GROUP_MEMBER',

  // Reactions & Attachments
  CREATE_REACTION: 'CREATE_REACTION',
  DELETE_REACTION: 'DELETE_REACTION',
  ATTACH_FILES: 'ATTACH_FILES',
  CREATE_ATTACHMENT: 'CREATE_ATTACHMENT',
  DELETE_ATTACHMENT: 'DELETE_ATTACHMENT',

  // Custom Emojis
  MANAGE_EMOJIS: 'MANAGE_EMOJIS',

  // Moderation
  BAN_USER: 'BAN_USER',
  KICK_USER: 'KICK_USER',
  TIMEOUT_USER: 'TIMEOUT_USER',
  UNBAN_USER: 'UNBAN_USER',
  PIN_MESSAGE: 'PIN_MESSAGE',
  UNPIN_MESSAGE: 'UNPIN_MESSAGE',
  DELETE_ANY_MESSAGE: 'DELETE_ANY_MESSAGE',
  VIEW_BAN_LIST: 'VIEW_BAN_LIST',
  VIEW_MODERATION_LOGS: 'VIEW_MODERATION_LOGS',
  MUTE_PARTICIPANT: 'MUTE_PARTICIPANT',

  // Voice / Replay
  CAPTURE_REPLAY: 'CAPTURE_REPLAY',

  // Soundboard
  CREATE_SOUNDBOARD_SOUND: 'CREATE_SOUNDBOARD_SOUND',
  DELETE_SOUNDBOARD_SOUND: 'DELETE_SOUNDBOARD_SOUND',
  READ_SOUNDBOARD_SOUND: 'READ_SOUNDBOARD_SOUND',

  // Instance Administration
  READ_INSTANCE_SETTINGS: 'READ_INSTANCE_SETTINGS',
  UPDATE_INSTANCE_SETTINGS: 'UPDATE_INSTANCE_SETTINGS',
  READ_INSTANCE_STATS: 'READ_INSTANCE_STATS',
  MANAGE_USER_STORAGE: 'MANAGE_USER_STORAGE',
} as const;

export type RbacAction = typeof RBAC_ACTIONS[keyof typeof RBAC_ACTIONS];

// Grouped permissions for better UI display
export const PERMISSION_GROUPS = {
  'Messages': [
    RBAC_ACTIONS.CREATE_MESSAGE,
    RBAC_ACTIONS.DELETE_MESSAGE,
    RBAC_ACTIONS.READ_MESSAGE,
  ],
  'Channels': [
    RBAC_ACTIONS.CREATE_CHANNEL,
    RBAC_ACTIONS.UPDATE_CHANNEL,
    RBAC_ACTIONS.DELETE_CHANNEL,
    RBAC_ACTIONS.READ_CHANNEL,
    RBAC_ACTIONS.JOIN_CHANNEL,
    RBAC_ACTIONS.MANAGE_CHANNEL_PERMISSIONS,
    RBAC_ACTIONS.MANAGE_WEBHOOKS,
  ],
  'Voice': [
    RBAC_ACTIONS.SPEAK,
    RBAC_ACTIONS.VIDEO,
    RBAC_ACTIONS.SCREEN_SHARE,
  ],
  'Community': [
    RBAC_ACTIONS.UPDATE_COMMUNITY,
    RBAC_ACTIONS.DELETE_COMMUNITY,
    RBAC_ACTIONS.READ_COMMUNITY,
    RBAC_ACTIONS.READ_ALL_COMMUNITIES,
  ],
  'Members': [
    RBAC_ACTIONS.CREATE_MEMBER,
    RBAC_ACTIONS.UPDATE_MEMBER,
    RBAC_ACTIONS.DELETE_MEMBER,
    RBAC_ACTIONS.READ_MEMBER,
  ],
  'Roles': [
    RBAC_ACTIONS.CREATE_ROLE,
    RBAC_ACTIONS.UPDATE_ROLE,
    RBAC_ACTIONS.DELETE_ROLE,
    RBAC_ACTIONS.READ_ROLE,
  ],
  'Users': [
    RBAC_ACTIONS.UPDATE_USER,
    RBAC_ACTIONS.DELETE_USER,
    RBAC_ACTIONS.READ_USER,
  ],
  'Invites': [
    RBAC_ACTIONS.CREATE_INVITE,
    RBAC_ACTIONS.DELETE_INVITE,
    RBAC_ACTIONS.CREATE_INSTANCE_INVITE,
    RBAC_ACTIONS.DELETE_INSTANCE_INVITE,
    RBAC_ACTIONS.READ_INSTANCE_INVITE,
    RBAC_ACTIONS.UPDATE_INSTANCE_INVITE,
  ],
  'Content': [
    RBAC_ACTIONS.CREATE_REACTION,
    RBAC_ACTIONS.DELETE_REACTION,
    RBAC_ACTIONS.ATTACH_FILES,
    RBAC_ACTIONS.CREATE_ATTACHMENT,
    RBAC_ACTIONS.DELETE_ATTACHMENT,
    RBAC_ACTIONS.MANAGE_EMOJIS,
  ],
  'Alias Groups': [
    RBAC_ACTIONS.CREATE_ALIAS_GROUP,
    RBAC_ACTIONS.UPDATE_ALIAS_GROUP,
    RBAC_ACTIONS.DELETE_ALIAS_GROUP,
    RBAC_ACTIONS.READ_ALIAS_GROUP,
    RBAC_ACTIONS.CREATE_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.DELETE_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.READ_ALIAS_GROUP_MEMBER,
    RBAC_ACTIONS.UPDATE_ALIAS_GROUP_MEMBER,
  ],
  'Moderation': [
    RBAC_ACTIONS.BAN_USER,
    RBAC_ACTIONS.UNBAN_USER,
    RBAC_ACTIONS.KICK_USER,
    RBAC_ACTIONS.TIMEOUT_USER,
    RBAC_ACTIONS.PIN_MESSAGE,
    RBAC_ACTIONS.UNPIN_MESSAGE,
    RBAC_ACTIONS.DELETE_ANY_MESSAGE,
    RBAC_ACTIONS.VIEW_BAN_LIST,
    RBAC_ACTIONS.VIEW_MODERATION_LOGS,
    RBAC_ACTIONS.MUTE_PARTICIPANT,
  ],
  'Soundboard': [
    RBAC_ACTIONS.READ_SOUNDBOARD_SOUND,
    RBAC_ACTIONS.CREATE_SOUNDBOARD_SOUND,
    RBAC_ACTIONS.DELETE_SOUNDBOARD_SOUND,
  ],
};

// Human readable action names
export const ACTION_LABELS: Record<RbacAction, string> = {
  // Messages
  [RBAC_ACTIONS.CREATE_MESSAGE]: 'Send messages',
  [RBAC_ACTIONS.DELETE_MESSAGE]: 'Delete messages',
  [RBAC_ACTIONS.READ_MESSAGE]: 'Read messages',

  // Channels
  [RBAC_ACTIONS.CREATE_CHANNEL]: 'Create channels',
  [RBAC_ACTIONS.UPDATE_CHANNEL]: 'Edit channels',
  [RBAC_ACTIONS.DELETE_CHANNEL]: 'Delete channels',
  [RBAC_ACTIONS.READ_CHANNEL]: 'View channels',
  [RBAC_ACTIONS.JOIN_CHANNEL]: 'Join channels',
  [RBAC_ACTIONS.MANAGE_CHANNEL_PERMISSIONS]: 'Manage channel permissions',
  [RBAC_ACTIONS.MANAGE_WEBHOOKS]: 'Manage webhooks',

  // Voice
  [RBAC_ACTIONS.SPEAK]: 'Speak in voice',
  [RBAC_ACTIONS.VIDEO]: 'Use video',
  [RBAC_ACTIONS.SCREEN_SHARE]: 'Share screen',

  // Community
  [RBAC_ACTIONS.CREATE_COMMUNITY]: 'Create communities',
  [RBAC_ACTIONS.UPDATE_COMMUNITY]: 'Edit community',
  [RBAC_ACTIONS.DELETE_COMMUNITY]: 'Delete community',
  [RBAC_ACTIONS.READ_COMMUNITY]: 'View community',
  [RBAC_ACTIONS.READ_ALL_COMMUNITIES]: 'View all communities',

  // Members
  [RBAC_ACTIONS.CREATE_MEMBER]: 'Add members',
  [RBAC_ACTIONS.UPDATE_MEMBER]: 'Edit members',
  [RBAC_ACTIONS.DELETE_MEMBER]: 'Remove members',
  [RBAC_ACTIONS.READ_MEMBER]: 'View members',

  // Roles
  [RBAC_ACTIONS.CREATE_ROLE]: 'Create roles',
  [RBAC_ACTIONS.UPDATE_ROLE]: 'Edit roles',
  [RBAC_ACTIONS.DELETE_ROLE]: 'Delete roles',
  [RBAC_ACTIONS.READ_ROLE]: 'View roles',

  // Users
  [RBAC_ACTIONS.UPDATE_USER]: 'Edit users',
  [RBAC_ACTIONS.DELETE_USER]: 'Delete users',
  [RBAC_ACTIONS.READ_USER]: 'View users',

  // Invites
  [RBAC_ACTIONS.CREATE_INVITE]: 'Create invites',
  [RBAC_ACTIONS.DELETE_INVITE]: 'Delete invites',
  [RBAC_ACTIONS.CREATE_INSTANCE_INVITE]: 'Create instance invites',
  [RBAC_ACTIONS.DELETE_INSTANCE_INVITE]: 'Delete instance invites',
  [RBAC_ACTIONS.READ_INSTANCE_INVITE]: 'View invites',
  [RBAC_ACTIONS.UPDATE_INSTANCE_INVITE]: 'Update invites',

  // Content
  [RBAC_ACTIONS.CREATE_REACTION]: 'Add reactions',
  [RBAC_ACTIONS.DELETE_REACTION]: 'Remove reactions',
  [RBAC_ACTIONS.ATTACH_FILES]: 'Attach files',
  [RBAC_ACTIONS.CREATE_ATTACHMENT]: 'Upload files',
  [RBAC_ACTIONS.DELETE_ATTACHMENT]: 'Delete files',
  [RBAC_ACTIONS.MANAGE_EMOJIS]: 'Manage custom emojis',

  // Alias Groups
  [RBAC_ACTIONS.CREATE_ALIAS_GROUP]: 'Create mention groups',
  [RBAC_ACTIONS.UPDATE_ALIAS_GROUP]: 'Edit mention groups',
  [RBAC_ACTIONS.DELETE_ALIAS_GROUP]: 'Delete mention groups',
  [RBAC_ACTIONS.READ_ALIAS_GROUP]: 'View mention groups',
  [RBAC_ACTIONS.CREATE_ALIAS_GROUP_MEMBER]: 'Add to mention groups',
  [RBAC_ACTIONS.DELETE_ALIAS_GROUP_MEMBER]: 'Remove from mention groups',
  [RBAC_ACTIONS.READ_ALIAS_GROUP_MEMBER]: 'View mention group members',
  [RBAC_ACTIONS.UPDATE_ALIAS_GROUP_MEMBER]: 'Edit mention group members',

  // Moderation
  [RBAC_ACTIONS.BAN_USER]: 'Ban users',
  [RBAC_ACTIONS.UNBAN_USER]: 'Unban users',
  [RBAC_ACTIONS.KICK_USER]: 'Kick users',
  [RBAC_ACTIONS.TIMEOUT_USER]: 'Timeout users',
  [RBAC_ACTIONS.PIN_MESSAGE]: 'Pin messages',
  [RBAC_ACTIONS.UNPIN_MESSAGE]: 'Unpin messages',
  [RBAC_ACTIONS.DELETE_ANY_MESSAGE]: 'Delete any message',
  [RBAC_ACTIONS.VIEW_BAN_LIST]: 'View ban list',
  [RBAC_ACTIONS.VIEW_MODERATION_LOGS]: 'View moderation logs',
  [RBAC_ACTIONS.MUTE_PARTICIPANT]: 'Mute voice participants',

  // Voice / Replay
  [RBAC_ACTIONS.CAPTURE_REPLAY]: 'Capture voice replays',

  // Soundboard
  [RBAC_ACTIONS.READ_SOUNDBOARD_SOUND]: 'View soundboard sounds',
  [RBAC_ACTIONS.CREATE_SOUNDBOARD_SOUND]: 'Add soundboard sounds',
  [RBAC_ACTIONS.DELETE_SOUNDBOARD_SOUND]: 'Delete soundboard sounds',

  // Instance Administration
  [RBAC_ACTIONS.READ_INSTANCE_SETTINGS]: 'View instance settings',
  [RBAC_ACTIONS.UPDATE_INSTANCE_SETTINGS]: 'Edit instance settings',
  [RBAC_ACTIONS.READ_INSTANCE_STATS]: 'View instance stats',
  [RBAC_ACTIONS.MANAGE_USER_STORAGE]: 'Manage user storage',
};